apiVersion: v1
data:
  basic.txt: <base64-encoded-value> # encode with: printf 'username=<api-key>\npassword=<api-secret>' | base64
kind: Secret
metadata:
  name: cloud-rest-access
  namespace: confluent
type: Opaque
