apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: myschema-value
  namespace: confluent
spec:
  # The subject name in Schema Registry
  name: myschema-value
  compatibilityLevel: BACKWARD
  data:
    configRef: user-schema-config
    format: avro
  schemaRegistryRest:
    endpoint: <schema-registry-endpoint>
    authentication:
      type: basic
      basic:
        secretRef: ccloud-sr-credentials
