apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: user-value-schema
  namespace: confluent
spec:
  # The subject name in Schema Registry
  name: user-value 
  compatibilityLevel: BACKWARD
  data:
    configRef: user-schema-config
    format: avro
  schemaRegistryRest:
    endpoint: https://psrc-40382p5.eastus2.azure.confluent.cloud
    authentication:
      type: basic
      basic:
        secretRef: ccloud-sr-credentials
